### ISSUE TITLE
Unpooled proportion plot

### ISSUE THREAD

**Issue by Chazz-cloud** [jig4003/Ragas#1]
Hi, 
When I run an Unpooled proportion plot, there is always an error: no applicable method for 'droplevels' applied to an object of class "character", but this error does not appear in pooled proportion plot. Could you please guide me fix it?
I really appreciate any help you can provide.

**Comment by jig4003** [comment]
Is the variable/metadata column you passed to the "unpool.by" argument a character? If so, can you try converting it to a factor? Let me know if the issue goes away.
